rem Please "Run as Aadministrator"...
net stop sim756.WindowsServiceRESTServerSample
c:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe -u ..\bin\Debug\sim756.WindowsServiceRESTServerSample.exe